---
title: "ps4"
author: "Andres Silva"
date: "2024-06-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())

require(pacman)
p_load(pacman, rio, data.table, tidyverse,
       sf, rvest, ggplot2,
       mapview, tmaptools, osmdata)

```

## Problem set 4:

Esta página contiene todo el código del último problem set del curso.

## pUNTO 1:

```{r 1.1}


#1.1.
url <- "https://eduard-martinez.github.io/pset-4.html"

html <- read_html(url)

table <- html %>% html_table()
table <- table[[1]] 
url_full <- as.matrix(table$url)
## Al haber extrído las urls de la tabla, ya aseguramos que solo están las que contienen
# la extensión de propiedad. Por esto, url_subset = url_full


```

```{r 1.2}

## Al haber extrído las urls de la tabla, ya aseguramos que solo están las que contienen
# la extensión de propiedad. Por esto, url_subset = url_full

url_subset <- url_full

```



```{r 1.3}

lista_tablas <- list()
  
for (i in 1:length(url_subset)) {
  
  htread <- read_html(url_subset[i])
  
  lista_tablas[i] <- html_table(htread)
  
}
  
```

```{r 1.4}


db_house <- rbindlist(lista_tablas, fill=TRUE, idcol=TRUE)

```

## PUNTO 2:

```{r 2.1}

sf_house <- st_as_sf(db_house, coords = c("lon","lat"), crs = 4326)

```


```{r 2.2}

bog <- opq(bbox = getbb("Bogota Colombia")) %>%
       add_osm_feature(key="boundary", value="administrative") %>% 
       osmdata_sf()
bog <- bog$osm_multipolygons %>% subset(admin_level==9 & !osm_id %in% 16011743:16011744)



ggplot() +   geom_sf(mapping = aes(),data = bog) + geom_sf(mapping = aes(fill = price), data = sf_house) 
#NOTA: FALT EXPORTAAAAAR

```
